### ISSUE TITLE
[Minecraft]: Could not pass event PlayerInteractEvent to FusionPixelmon v1.11

### ISSUE THREAD

**Issue by erposse90** [BrendonCurmi/FusionPixelmon#59] opened 2021-01-04 22:09 UTC
i, i've a server magma with fusion pixelmon v1.11, it's work good but sometime give this error:

04.01 22:06:38 [Server] Server thread/ERROR [Minecraft]: Could not pass event PlayerInteractEvent to FusionPixelmon v1.11
04.01 22:06:38 [Server] INFO  org.bukkit.event.EventException: null
04.01 22:06:38 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:46f4149]
04.01 22:06:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:46f4149]
04.01 22:06:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:46f4149]
04.01 22:06:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:263) [CraftEventFactory.class:46f4149]
04.01 22:06:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:230) [CraftEventFactory.class:46f4149]
04.01 22:06:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [CraftEventFactory.class:46f4149]
04.01 22:06:38 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_175087_a(NetHandlerPlayServer.java:1652) [pa.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.network.play.client.CPacketAnimation.func_148833_a(SourceFile:32) [ly.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.network.play.client.CPacketAnimation.func_148833_a(SourceFile:9) [ly.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
04.01 22:06:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
04.01 22:06:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
04.01 22:06:38 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924) [MinecraftServer.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) [MinecraftServer.class:?]
04.01 22:06:38 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
04.01 22:06:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
04.01 22:06:38 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by BrendonCurmi** [comment] 2021-01-04 22:14
What FusionPixelmon type (Forge, Sponge, etc)? When does the error message show?

**Comment by erposse90** [comment] 2021-01-05 01:49
it is the spigot version (I have a magma server as already mentioned);  the error occurs in the console randomly, with no visible effects in the game, perhaps with extra lagg, and without specific fusion actions being made (for example, commands are used etc.)

**Comment by erposse90** [comment] 2021-01-06 23:51
I have found that it is the wielding of enchanted objects that triggers the error!!!

**Comment by BrendonCurmi** [comment] 2021-01-17 10:45
Can you show the full error message? Because you only showed the top part

**Comment by BrendonCurmi** [comment] 2021-01-17 11:07
Nevermind, reproduced it and fixed it. It will be included in the next version. Thanks

**Closed** 2021-01-17 11:18 UTC
Labels: bug

**Comment by erposse90** [comment] 2021-01-17 13:35
Perfect tnks
